baseURL = 'https://help.econumo.com/'
title = 'Econumo'
theme = 'hugo-book'

languageCode = 'en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    baseURL = 'https://help.econumo.com/'
    languageName = 'English'
    contentDir = 'content/en/'
    weight = 1
  [languages.ru]
    baseURL = 'https://help.econumo.com/ru/'
    languageName = 'Русский'
    contentDir = 'content/ru/'
    weight = 2
