baseURL = 'https://econumo.app/help/'
title = 'Econumo'
theme = 'hugo-book'

languageCode = 'en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    baseURL = 'https://econumo.app/help/'
    languageName = 'English'
    weight = 1
  [languages.ru]
    baseURL = 'https://econumo.app/help/ru/'
    languageName = 'Русский'
    weight = 2
