---
version: '3'

tasks:
    up:
        desc: "Start"
        cmds:
          - hugo mod clean
          - hugo server --minify -D -v -w --disableFastRender --theme hugo-book

    build:
        desc: "Build"
        cmds:
          - hugo mod clean
          - hugo --minify --theme hugo-book
